cmake_minimum_required(VERSION 3.14)

macro(add_static_lib LIB_NAME LIB_PATH)
add_library(${LIB_NAME} STATIC IMPORTED)
set_target_properties(${LIB_NAME}  PROPERTIES IMPORTED_LOCATION ${LIB_PATH})
endmacro(add_static_lib)

macro(add_dynamic_lib LIB_NAME LIB_PATH)
add_library(${LIB_NAME} SHARED IMPORTED)
set_target_properties(${LIB_NAME}  PROPERTIES IMPORTED_LOCATION ${LIB_PATH})
endmacro(add_dynamic_lib)

macro(add_static_libs LIB_NAME LIB_DIR LIB1_NAME LIB2_NAME LIB3_NAME)
if(NOT MSVC)
    add_static_lib(${LIB_NAME} ${LIB_DIR}/${LIB1_NAME})
elseif(NOT ${CMAKE_BUILD_TYPE} MATCHES "Debug")
    add_static_lib(${LIB_NAME} ${LIB_DIR}/${LIB2_NAME})
else()
    add_static_lib(${LIB_NAME} ${LIB_DIR}/${LIB3_NAME})
endif(NOT MSVC)
endmacro(add_static_libs)

macro(add_dynamic_libs LIB_NAME LIB_DIR LIB1_NAME LIB2_NAME LIB3_NAME)
if(NOT MSVC)
    add_dynamic_lib(${LIB_NAME} ${LIB_DIR}/${LIB1_NAME})
elseif(NOT ${CMAKE_BUILD_TYPE} MATCHES "Debug")
    add_dynamic_lib(${LIB_NAME} ${LIB_DIR}/${LIB2_NAME})
else()
    add_dynamic_lib(${LIB_NAME} ${LIB_DIR}/${LIB3_NAME})
endif(NOT MSVC)
endmacro(add_dynamic_libs)

macro(subdirlist result curdir)
    file(GLOB children RELATIVE ${curdir} ${curdir}/*)
    set(dirlist "")
    foreach(child ${children})
        if(IS_DIRECTORY ${curdir}/${child})
            list(APPEND dirlist ${child})
        endif()
    endforeach()
    set(${result} ${dirlist})
endmacro(subdirlist)

